"""addiding some few entries to products

Revision ID: 0ae9a65a8ae6
Revises: fbbd7212c148
Create Date: 2024-10-09 11:51:09.370428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae9a65a8ae6'
down_revision = 'fbbd7212c148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('slug')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
